"""
Standard cell blackbox definitions for TRIT-TC and TRIT-TS benchmark suites.
Extracted from LEDA 250nm technology library used in DATE 2018 TRIT paper.
"""

TRIT_BLACKBOX_DEFINITIONS = {   'and2s1': {'ports': ['DIN1', 'DIN2', 'Q']},
    'and2s2': {'ports': ['DIN1', 'DIN2', 'Q']},
    'and2s3': {'ports': ['DIN1', 'DIN2', 'Q']},
    'and3s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'and3s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'and3s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'and4s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'and4s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'and5s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'and9s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'DIN7', 'DIN8', 'DIN9', 'Q']},
    'aoai1112s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'aoai122s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'aoi123s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'aoi13s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'aoi13s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'aoi211s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'aoi211s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'aoi21s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'aoi21s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'aoi221s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'aoi222s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'aoi22s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'aoi22s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'aoi23s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'aoi33s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'aoi42s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'aoi42s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'dffcs2': {'ports': ['CLK', 'CLRB', 'DIN', 'Q']},
    'dffles2': {'ports': ['CLK', 'DIN', 'EB', 'Q', 'QN']},
    'dffs2': {'ports': ['CLK', 'DIN', 'Q', 'QN']},
    'dsmxc31s2': {'ports': ['CLK', 'DIN1', 'DIN2', 'Q']},
    'hi1s1': {'ports': ['DIN', 'Q']},
    'i1s1': {'ports': ['DIN', 'Q']},
    'i1s11': {'ports': ['DIN', 'Q']},
    'i1s12': {'ports': ['DIN', 'Q']},
    'i1s3': {'ports': ['DIN', 'Q']},
    'ib1s1': {'ports': ['DIN', 'Q']},
    'ib1s2': {'ports': ['DIN', 'Q']},
    'ib1s5': {'ports': ['DIN', 'Q']},
    'ib1s9': {'ports': ['DIN', 'Q']},
    'mx21s3': {'ports': ['DIN1', 'DIN2', 'Q', 'SIN']},
    'mx41s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q', 'SIN0', 'SIN1']},
    'mx41s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q', 'SIN0', 'SIN1']},
    'mxi21s1': {'ports': ['DIN1', 'DIN2', 'Q', 'SIN']},
    'mxi21s2': {'ports': ['DIN1', 'DIN2', 'Q', 'SIN']},
    'mxi21s3': {'ports': ['DIN1', 'DIN2', 'Q', 'SIN']},
    'mxi41s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q', 'SIN0', 'SIN1']},
    'mxi41s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q', 'SIN0', 'SIN1']},
    'nb1s1': {'ports': ['DIN', 'Q']},
    'nnd2s1': {'ports': ['DIN1', 'DIN2', 'Q']},
    'nnd2s2': {'ports': ['DIN1', 'DIN2', 'Q']},
    'nnd2s3': {'ports': ['DIN1', 'DIN2', 'Q']},
    'nnd3s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'nnd3s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'nnd3s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'nnd4s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'nnd4s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'nnd4s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'nnd5s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'nor2s1': {'ports': ['DIN1', 'DIN2', 'Q']},
    'nor2s2': {'ports': ['DIN1', 'DIN2', 'Q']},
    'nor2s3': {'ports': ['DIN1', 'DIN2', 'Q']},
    'nor3s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'nor3s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'nor3s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'nor4s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'nor4s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'nor5s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'nor5s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'nor6s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'nor6s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'oai1112s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'oai1112s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'oai13s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'oai211s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'oai211s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'oai21s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'oai21s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'oai221s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'oai222s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'oai22s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'oai22s2': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'oai24s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'oai321s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'oai322s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'DIN7', 'Q']},
    'oai32s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'oai33s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'oai33s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'DIN6', 'Q']},
    'or2s1': {'ports': ['DIN1', 'DIN2', 'Q']},
    'or2s2': {'ports': ['DIN1', 'DIN2', 'Q']},
    'or2s3': {'ports': ['DIN1', 'DIN2', 'Q']},
    'or3s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'or3s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'Q']},
    'or4s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'or4s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'Q']},
    'or5s1': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'or5s3': {'ports': ['DIN1', 'DIN2', 'DIN3', 'DIN4', 'DIN5', 'Q']},
    'sdffs1': {'ports': ['CLK', 'DIN', 'Q', 'QN', 'SDIN', 'SSEL']},
    'xnr2s1': {'ports': ['DIN1', 'DIN2', 'Q']},
    'xnr2s2': {'ports': ['DIN1', 'DIN2', 'Q']},
    'xnr2s3': {'ports': ['DIN1', 'DIN2', 'Q']},
    'xor2s1': {'ports': ['DIN1', 'DIN2', 'Q']},
    'xor2s2': {'ports': ['DIN1', 'DIN2', 'Q']},
    'xor2s3': {'ports': ['DIN1', 'DIN2', 'Q']}}

def get_trit_blackboxes():
    """Return the complete TRIT blackbox definitions dictionary."""
    return TRIT_BLACKBOX_DEFINITIONS
