#!/usr/bin/env python3
"""CLI wrapper for explanation generation (Method 1)"""

import argparse
import os
import json
import shutil


def main():
    """Main entry point for method1-explain command"""
    parser = argparse.ArgumentParser(
        prog='method1-explain',
        description='Generate explanations from Method 1 KB processing output',
        epilog='Organizes KB output into explanations directory'
    )
    parser.add_argument('-i', '--input', required=True, 
                       help='Input folder with KB processing output (arch_decisions.json, etc.)')
    parser.add_argument('-o', '--output', required=True, 
                       help='Output folder for explanations')
    
    args = parser.parse_args()
    
    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    
    # Check if arch_decisions.json exists (generated by KB processing)
    arch_decisions_path = os.path.join(args.input, 'arch_decisions.json')
    if not os.path.exists(arch_decisions_path):
        raise FileNotFoundError(
            f"arch_decisions.json not found in {args.input}. "
            "Run method1-kb first to generate KB processing output."
        )
    
    # Copy/link explanation files from KB output
    # The KB processing already generates the explanations as arch_decisions.json
    files_to_copy = [
        'arch_decisions.json',  # Main explanations
        'arch_preds.json',      # Predictions
        'similar.json',         # Empty structure for compatibility
    ]
    
    for filename in files_to_copy:
        src = os.path.join(args.input, filename)
        dst = os.path.join(args.output, filename)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f"Copied {filename} to explanations folder")
        else:
            print(f"Warning: {filename} not found in {args.input}")
    
    # Create an index file for easy reference
    index = {
        "method": "property-based (Method 1)",
        "explanation_file": "arch_decisions.json",
        "predictions_file": "arch_preds.json",
        "description": "Each decision contains property votes, effectiveness, and explainability scores"
    }
    
    with open(os.path.join(args.output, 'index.json'), 'w') as f:
        json.dump(index, f, indent=2)
    
    print(f"\nExplanations organized in: {args.output}")
    print(f"Main explanations: {os.path.join(args.output, 'arch_decisions.json')}")


if __name__ == '__main__':
    main()
